// Generated by LiveScript 1.5.0
(function(){
  define(function(require){
    var Subscription;
    return Subscription = (function(){
      Subscription.displayName = 'Subscription';
      var prototype = Subscription.prototype, constructor = Subscription;
      function Subscription(_sup, _handler){
        this._sup = _sup;
        this._handler = _handler;
        this.active = true;
      }
      Subscription.prototype.send = function(type, path, value){
        if (this.active) {
          if (this._handler instanceof Function) {
            return this._handler.apply(this, arguments);
          } else {
            return this._handler[type](path, value);
          }
        }
      };
      Subscription.prototype.cancel = function(){
        return this._sup.unsubscribe(this);
      };
      Subscription.prototype.pause = function(){
        return this.active = false;
      };
      Subscription.prototype.unpause = function(){
        return this.active = true;
      };
      return Subscription;
    }());
  });
}).call(this);
