// Generated by LiveScript 1.5.0
(function(){
  define(function(require){
    var WsProxy;
    return WsProxy = (function(){
      WsProxy.displayName = 'WsProxy';
      var prototype = WsProxy.prototype, constructor = WsProxy;
      function WsProxy(_object, channel, _client, startOn){
        var this$ = this;
        this._object = _object;
        this._client = _client;
        startOn == null && (startOn = true);
        this._subscription = null;
        this._channel = "/sup" + channel;
        if (startOn) {
          this.connect();
        }
        this._subscribe("/unsubscribe", function(){
          return this$.disconnect;
        });
        this._subscribe("/init", function(){
          this$.connect();
          return this$.init();
        });
      }
      WsProxy.prototype.init = function(){
        return this._send("/init", this._object);
      };
      WsProxy.prototype.connect = function(){
        var this$ = this;
        if (!this._subscription) {
          return this._subscription = this._object.subscribe(function(type, path, value){
            return this$._send("/update", {
              type: type,
              path: path,
              value: type !== "remove" ? value : void 8
            });
          });
        }
      };
      WsProxy.prototype.disconnect = function(){
        this._subscription.cancel();
        return this._subscription = null;
      };
      WsProxy.prototype._subscribe = function(channel, fn){
        return this._client.on(this._channel + channel, fn);
      };
      WsProxy.prototype._send = function(channel, data){
        return this._client.emit(this._channel + channel, data);
      };
      return WsProxy;
    }());
  });
}).call(this);
